<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="Microsoft.MixedReality.WebRTC" Version="2.0.2" />
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(NuGetPackageRoot)microsoft.mixedreality.webrtc\2.0.2\runtimes\win10-x64\native\*.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="src\**\*.cs" />
    <ApplicationDefinition Include="src\App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <Link>App.xaml</Link>
    </ApplicationDefinition>
    <Page Include="src\UI\MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
      <Link>MainWindow.xaml</Link>
    </Page>
    <Page Include="src\UI\SelectionWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
      <Link>SelectionWindow.xaml</Link>
    </Page>
    <Page Include="src\UI\ViewerWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
      <Link>ViewerWindow.xaml</Link>
    </Page>
  </ItemGroup>

  <Target Name="CopyWebRTCNative" AfterTargets="Build">
    <ItemGroup>
      <WebRTCNative Include="$(NuGetPackageRoot)microsoft.mixedreality.webrtc\2.0.2\runtimes\win10-x64\native\*.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(WebRTCNative)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>

</Project>
